extend type Query {
    bookings(roleName:RoleName, page:Int!, size:Int!):ListBooking
    upcomingBookings(daysLatter:Int!):ListBooking
    booking(bookingId:ID!):Booking
}

type ListBooking{
    data:[Booking]
    pageInfo:PageInfo
}

type Booking{
    id:ID!
    amount: BigDecimal!
    basisPrice: BigDecimal!
    usageDate: String!
    startTime: String!
    endTime: String
    status: String!
    payMethod: String!
    createdAt: String!

    user:User
    packageInfo:FacilityPackage
    facility:Facility
    reviewEligibility:ReviewEligibility
}