spring.application.name=BookingPlatform
server.port=${PORT:8080}

# Tomcat
server.tomcat.threads.max=300
server.tomcat.threads.min-spare=50
server.tomcat.accept-count=200

# HikariCP
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=30000


# Database